global:
  scrape_interval: 15s  # Intervalo de recolección de datos

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']  # cAdvisor expone las métricas de Docker
